fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

loisirs:
    resource: "@LoisirsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
